name: shortie
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^4.7.2
  get_storage: ^2.1.1
  fluttertoast: ^8.2.12
  #  intl: ^0.19.0
  intl: ^0.20.2
  connectivity_plus: ^6.1.4
  url_launcher: ^6.3.1
  lottie: ^3.3.1
  #  chewie: ^1.8.1
  #  chewie: ^1.8.4
  chewie: ^1.11.3
  cached_network_image: ^3.4.1
  #  video_player: ^2.8.6
  #  video_player: ^2.9.1
  video_player: ^2.9.5
  shimmer: ^3.0.0
  country_picker: ^2.0.27
  dotted_border: ^2.1.0
  path_provider: ^2.1.5
  socket_io_client: ^3.1.2
  camera: ^0.11.1
  flutter_spinkit: ^5.2.1
  firebase_auth: ^5.5.3
  firebase_core: ^3.13.0
  preload_page_view: ^0.2.0
  firebase_messaging: ^15.2.5
  google_sign_in: ^6.3.0
  video_thumbnail: ^0.5.5
  image_picker: ^1.1.2
  ffmpeg_kit_flutter_new: ^1.4.1
  audioplayers: ^6.4.0
  deepar_flutter: ^0.0.5
  #  zego_express_engine: ^3.14.5+2
  zego_express_engine: ^3.20.5
  encrypt: ^5.0.3
  native_device_orientation: ^2.0.3
  flutter_svg: ^2.1.0
  record: ^6.0.0
  webview_flutter: ^4.11.0
  flutter_local_notifications: ^19.2.0
  razorpay_flutter: ^1.4.0
  flutter_stripe: ^11.5.0
  in_app_purchase: ^3.2.2
  dio: ^5.8.0+1
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.0.0
  date_picker_plus: ^4.2.0
  svgaplayer_flutter: ^2.2.0
  vibration: ^3.1.3
  screenshot: ^3.0.0
  gallery_saver: ^2.3.2
  flutter_launcher_icons: ^0.14.3
  firebase_crashlytics: ^4.3.5
  share_plus: ^11.0.0
  flutter_branch_sdk: ^8.4.1
  flutter_share: ^2.0.0
  readmore: ^3.0.0
  device_info_plus: ^11.4.0
  blurrycontainer: ^2.1.0
  flutterwave_standard: ^1.1.0
  intl_phone_field: ^3.2.0
  flutter_otp_text_field: ^1.5.1+1
  video_trimmer: ^5.0.0
  wakelock_plus: ^1.3.2
  loading_animation_widget: ^1.3.0

dependency_overrides:
  http: ^1.4.0
  archive: ^4.0.7
  cupertino_icons: ^1.0.8
  permission_handler: ^12.0.0+1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/ic_app_logo.webp"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/lottie/
    - assets/effects/

  fonts:
    - family: SfProRegular
      fonts:
        - asset: assets/fonts/Sf-Pro-Regular.OTF

    - family: SfProMedium
      fonts:
        - asset: assets/fonts/Sf-Pro-Medium.OTF

    - family: SfProBold
      fonts:
        - asset: assets/fonts/Sf-Pro-Bold.OTF
